### ISSUE TITLE
cannot inflect kanzuru

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#449]
Aedict inflector cannot inflect -zuru verbs:

```
java.lang.RuntimeException: zyunzuru is not ichidan
at sk.baka.aedict.inflection.VerbInflection$AbstractBaseInflector.getIchidanForm1(VerbInflection.java:273)
at sk.baka.aedict.inflection.VerbInflection$Base1Inflector.inflectIchidan(VerbInflection.java:43)
at sk.baka.aedict.inflection.VerbInflection$AbstractBaseInflector.inflect(VerbInflection.java:324)
at sk.baka.aedict3.dict.VerbInflectionFragment.buildAndSetAdapterVerb(VerbInflectionFragment.java:242)
at sk.baka.aedict3.dict.VerbInflectionFragment.buildAndSetAdapter(VerbInflectionFragment.java:142)
at sk.baka.aedict3.dict.VerbInflectionFragment.onActivityCreated(VerbInflectionFragment.java:63)
```

**Comment by mvysny** [comment]
Fixed in 3.13
