### ISSUE TITLE
Dropbox Sync bug

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#524]
com.dropbox.sync.android.DbxRuntimeException$BadState: Uncaught exception in API callback.
at com.dropbox.sync.android.CoreAndroidUtil.exitOnFatalError(CoreAndroidUtil.java:156)
at com.dropbox.sync.android.CoreAssert.uncaughtExceptionInCallback(CoreAssert.java:94)
at com.dropbox.sync.android.NativeHttp.getNativeErrorInfo(NativeHttp.java:337)
at com.dropbox.sync.android.NativeHttp.handleHttpError(NativeHttp.java:302)
at com.dropbox.sync.android.NativeHttp.httpRequest(NativeHttp.java:164)
at com.dropbox.sync.android.NativeThreads.nativeRunThread(Native Method)
at com.dropbox.sync.android.NativeThreads.nativeRunThread(Native Method)
at com.dropbox.sync.android.NativeThreads.access$000(NativeThreads.java:17)
at com.dropbox.sync.android.NativeThreads$1.run(NativeThreads.java:148)
at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.NoClassDefFoundError: com/android/org/bouncycastle/asn1/x500/X500Name
at com.android.org.bouncycastle.asn1.x509.TBSCertificate.<init>(TBSCertificate.java:93)
at com.android.org.bouncycastle.asn1.x509.TBSCertificate.getInstance(TBSCertificate.java:64)
at com.android.org.bouncycastle.asn1.x509.Certificate.<init>(Certificate.java:61)
at com.android.org.bouncycastle.asn1.x509.Certificate.getInstance(Certificate.java:45)
at com.android.org.bouncycastle.jcajce.provider.asymmetric.x509.CertificateFactory.readDERCertificate(CertificateFactory.java:67)
at com.android.org.bouncycastle.jcajce.provider.asymmetric.x509.CertificateFactory.engineGenerateCertificate(CertificateFactory.java:215)
at java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:195)
at com.android.org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.decodeCertificate(BcKeyStoreSpi.java:367)
at com.android.org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.loadStore(BcKeyStoreSpi.java:711)
at com.android.org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.engineLoad(BcKeyStoreSpi.java:867)
at java.security.KeyStore.load(KeyStore.java:589)
at com.dropbox.sync.android.CoreStandardHttpRequestor$SSLSocketFactoryWrapper.loadKeyStore(CoreStandardHttpRequestor.java:534)
at com.dropbox.sync.android.CoreStandardHttpRequestor$SSLSocketFactoryWrapper.getInstance(CoreStandardHttpRequestor.java:511)
at com.dropbox.sync.android.CoreStandardHttpRequestor$SingleRequestImpl.prepRequest(CoreStandardHttpRequestor.java:399)
at com.dropbox.sync.android.CoreStandardHttpRequestor$SingleRequestImpl.startPost(CoreStandardHttpRequestor.java:236)
at com.dropbox.sync.android.CoreStandardHttpRequestor$SingleRequestImpl.startPost(CoreStandardHttpRequestor.java:153)
at com.dropbox.sync.android.NativeHttp.doPost(NativeHttp.java:416)
at com.dropbox.sync.android.NativeHttp.httpRequest(NativeHttp.java:159)
... 5 more

**Comment by mvysny** [comment]
Posted a question to the Dropbox forums, we will see: https://www.dropboxforum.com/hc/communities/public/questions/204126185-Dropbox-Sync-Android-crashes-on-one-Android-phone

**Comment by mvysny** [comment]
I do not believe this bug to be fixed, as Dropbox Sync is now deprecated. But, let's see what happens.

**Comment by mvysny** [comment]
"Anyway, regarding the issue itself, it is unlikely that we'll be able to fix that, since the SDK is deprecated, and it sounds like this issue is device-specific (since presumably it works fine elsewhere, so perhaps the underlying cause if out of our control anyway)."
In short, nope, they will not fix it. Sorry mate, closing as won't fix.
