### ISSUE TITLE
Failed to resolve kanji 🍏 :-D

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#565]
java.lang.RuntimeException: Loader failed: java.lang.RuntimeException: Multiple entries for kanji 🍏
at sk.baka.aedict3.util.android.list.CheckableListFragment.handleLoaderError(CheckableListFragment.java:94)
at sk.baka.aedict3.dict.AbstractEntryRefListFragment.handleDictionaryCrash(AbstractEntryRefListFragment.java:244)
at sk.baka.aedict3.search.SearchResultFragment.handleLoaderError(SearchResultFragment.java:155)
at sk.baka.aedict3.util.android.list.CheckableListFragment$1.onFailure(CheckableListFragment.java:113)
at sk.baka.aedict3.util.android.LoaderEx$Loader.onFailure(LoaderEx.java:181)
at sk.baka.aedict3.util.android.LoaderEx$Loader.access$100(LoaderEx.java:105)
at sk.baka.aedict3.util.android.LoaderEx$Loader$1.run(LoaderEx.java:158)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: java.lang.RuntimeException: Multiple entries for kanji 🍏
at sk.baka.aedict.search.KanjidicQuery$ResolveKanjis.find(KanjidicQuery.java:227)
at sk.baka.aedict.search.KanjidicQuery$ResolveKanjis.search(KanjidicQuery.java:190)
at sk.baka.aedict3.search.SearchResultFragment$MyLoader.loadItemsInBackground(SearchResultFragment.java:55)
at sk.baka.aedict3.util.android.LoaderEx$Loader.run(LoaderEx.java:129)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)

**Comment by mvysny** [comment]
Fixed in Aedict 3.36
