### ISSUE TITLE
NPE when updating progress review grid

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#578]
Affects Aedict 3.38.8

java.lang.RuntimeException: Unable to start activity ComponentInfo{sk.baka.aedict3/sk.baka.aedict3.jlptquiz.ProgressReviewGridActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2062)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2087)
	at android.app.ActivityThread.access$600(ActivityThread.java:133)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1198)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4783)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at sk.baka.aedict3.jlptquiz.ProgressReviewGridActivity.updateGrid(ProgressReviewGridActivity.java:165)
	at sk.baka.aedict3.jlptquiz.ProgressReviewGridActivity.access$200(ProgressReviewGridActivity.java:34)
	at sk.baka.aedict3.jlptquiz.ProgressReviewGridActivity$2.onCheckedChanged(ProgressReviewGridActivity.java:91)
	at android.widget.RadioGroup.setCheckedId(RadioGroup.java:174)
	at android.widget.RadioGroup.access$600(RadioGroup.java:54)
	at android.widget.RadioGroup$CheckedStateTracker.onCheckedChanged(RadioGroup.java:358)
	at android.widget.CompoundButton.setChecked(CompoundButton.java:147)
	at android.widget.CompoundButton.onRestoreInstanceState(CompoundButton.java:375)
	at android.view.View.dispatchRestoreInstanceState(View.java:12128)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2597)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2597)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2597)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2597)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2597)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2597)
	at android.view.View.restoreHierarchyState(View.java:12106)
	at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1728)
	at android.app.Activity.onRestoreInstanceState(Activity.java:935)
	at android.app.Activity.performRestoreInstanceState(Activity.java:907)
	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1130)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2040)
	... 11 more

**Comment by mvysny** [comment]
Fixed in Aedict 3.38.9
