### ISSUE TITLE
ClosedChannelException

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#579]
Aedict 3.38.10:

java.lang.RuntimeException: Loader failed: java.lang.RuntimeException: Failed to run query jp:WたW
	at sk.baka.aedict3.util.android.list.CheckableListFragment.handleLoaderError(CheckableListFragment.java:94)
	at sk.baka.aedict3.dict.AbstractEntryRefListFragment.handleDictionaryCrash(AbstractEntryRefListFragment.java:247)
	at sk.baka.aedict3.search.SearchResultFragment.handleLoaderError(SearchResultFragment.java:139)
	at sk.baka.aedict3.util.android.list.CheckableListFragment$1.onFailure(CheckableListFragment.java:113)
	at sk.baka.aedict3.util.android.LoaderEx$Loader.onFailure(LoaderEx.java:181)
	at sk.baka.aedict3.util.android.LoaderEx$Loader.access$100(LoaderEx.java:105)
	at sk.baka.aedict3.util.android.LoaderEx$Loader$1.run(LoaderEx.java:158)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5972)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by: java.lang.RuntimeException: Failed to run query jp:WたW
	at sk.baka.aedict.search.impl.EdictSearch.search(EdictSearch.java:95)
	at sk.baka.aedict.search.impl.EdictSearch.findByJapanese(EdictSearch.java:75)
	at sk.baka.aedict.search.SentenceAnalyzer.findLongestWord(SentenceAnalyzer.java:313)
	at sk.baka.aedict.search.SentenceAnalyzer.findLongestWord(SentenceAnalyzer.java:227)
	at sk.baka.aedict.search.SentenceAnalyzer.analyzeByWords(SentenceAnalyzer.java:111)
	at sk.baka.aedict.search.JMDictQuery.search(JMDictQuery.java:98)
	at sk.baka.aedict3.search.SearchResultFragment$MyLoader.loadItemsInBackground(SearchResultFragment.java:57)
	at sk.baka.aedict3.util.android.LoaderEx$Loader.run(LoaderEx.java:129)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.RuntimeException: Failed to run query jp:WたW: jp:"WたW"
	at sk.baka.aedict.search.lucene.LuceneSearchUtils.search(LuceneSearchUtils.java:164)
	at sk.baka.aedict.search.impl.LuceneCache$1.search(LuceneCache.java:87)
	at sk.baka.aedict.search.impl.EdictSearch.search(EdictSearch.java:89)
	... 12 more
Caused by: java.io.IOException: null: NIOFSIndexInput(path="/storage/emulated/0/Android/data/sk.baka.aedict3/files/aedict3/dictionaries/JMDICT/null/_4.prx")
	at org.apache.lucene.store.NIOFSDirectory$NIOFSIndexInput.readInternal(NIOFSDirectory.java:180)
	at org.apache.lucene.store.BufferedIndexInput.refill(BufferedIndexInput.java:270)
	at org.apache.lucene.store.BufferedIndexInput.readByte(BufferedIndexInput.java:40)
	at org.apache.lucene.store.DataInput.readVInt(DataInput.java:107)
	at org.apache.lucene.store.BufferedIndexInput.readVInt(BufferedIndexInput.java:217)
	at org.apache.lucene.index.SegmentTermPositions.readDeltaPosition(SegmentTermPositions.java:76)
	at org.apache.lucene.index.SegmentTermPositions.nextPosition(SegmentTermPositions.java:72)
	at org.apache.lucene.search.ExactPhraseScorer.phraseFreq(ExactPhraseScorer.java:344)
	at org.apache.lucene.search.ExactPhraseScorer.nextDoc(ExactPhraseScorer.java:154)
	at org.apache.lucene.search.Scorer.score(Scorer.java:89)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:581)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:383)
	at sk.baka.aedict.search.lucene.LuceneSearchUtils.cancelableSearch(LuceneSearchUtils.java:178)
	at sk.baka.aedict.search.lucene.LuceneSearchUtils.search(LuceneSearchUtils.java:153)
	... 14 more
Caused by: java.nio.channels.ClosedChannelException
	at java.nio.FileChannelImpl.checkOpen(FileChannelImpl.java:74)
	at java.nio.FileChannelImpl.readImpl(FileChannelImpl.java:296)
	at java.nio.FileChannelImpl.read(FileChannelImpl.java:287)
	at org.apache.lucene.store.NIOFSDirectory$NIOFSIndexInput.readInternal(NIOFSDirectory.java:162)
	... 27 more

**Comment by mvysny** [comment]
Fixed in 3.38.11
