### ISSUE TITLE
Reader: service not started

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#580]
java.lang.IllegalStateException: Invalid state: not started
	at sk.baka.aedictreader.floatingwindow.FloaterService.analyze(FloaterService.java:154)
	at sk.baka.aedictreader.reader.ReaderActivity$1.onSingleTapUp(ReaderActivity.java:81)
	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:595)
	at sk.baka.aedictreader.reader.ReaderActivity$2.onTouch(ReaderActivity.java:89)
	at android.view.View.dispatchTouchEvent(View.java:7685)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2066)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1515)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2457)
	at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2014)
	at android.view.View.dispatchPointerEvent(View.java:7870)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3940)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3829)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3425)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3475)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3444)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3529)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3452)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3586)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3425)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3475)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3444)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3452)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3425)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5541)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5521)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5492)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5615)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:182)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:137)
	at android.os.Looper.loop(Looper.java:124)
	at android.app.ActivityThread.main(ActivityThread.java:4998)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:811)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:627)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by mvysny** [comment]
Fixed in 1.3.3
