### ISSUE TITLE
Large number of entries (Select All) quiz issue

### ISSUE THREAD

**Issue by kuroi-hayabusa** [mvysny/aedict#587]
When selecting all entries of a notepad category for a quiz, if the number is large (500), the quiz does not start. You get intead the previous app window after a few seconds.

You can argue why do we need such long quizes (rather that use the 100 option) but I find it useful for review, and in any case I think this is a bug.

Thank you!

**Comment by mvysny** [comment]
Just to be clear - if you start the quiz via the upper-right menu "Notepad quiz" (the one which asks you to select notepad categories) this works okay?
On the other hand, if you long-touch an item in the notepad, then press "Select All" to select all 500 entries and then press "Quiz", this crashes? Is this correct?

**Comment by mvysny** [comment]
What is your setting of the quiz length? It should be 20 by default.

**Comment by mvysny** [comment]
The real issue here is
11-28 11:29:56.328 919-2156/? W/ActivityManager: Exception when starting activity sk.baka.aedict3/.jlptquiz.QuizActivity
                                                 android.os.TransactionTooLargeException
                                                     at android.os.BinderProxy.transactNative(Native Method)
                                                     at android.os.BinderProxy.transact(Binder.java:496)
                                                     at android.app.ApplicationThreadProxy.scheduleLaunchActivity(ApplicationThreadNative.java:797)
                                                     at com.android.server.am.ActivityStackSupervisor.realStartActivityLocked(ActivityStackSupervisor.java:1205)
                                                     at com.android.server.am.ActivityStackSupervisor.startSpecificActivityLocked(ActivityStackSupervisor.java:1305)
                                                     at com.android.server.am.ActivityStack.resumeTopActivityInnerLocked(ActivityStack.java:1924)
                                                     at com.android.server.am.ActivityStack.resumeTopActivityLocked(ActivityStack.java:1476)
                                                     at com.android.server.am.ActivityStackSupervisor.resumeTopActivitiesLocked(ActivityStackSupervisor.java:2501)
                                                     at com.android.server.am.ActivityStack.completePauseLocked(ActivityStack.java:1010)
                                                     at com.android.server.am.ActivityStack.activityPausedLocked(ActivityStack.java:903)
                                                     at com.android.server.am.ActivityManagerService.activityPaused(ActivityManagerService.java:6463)
                                                     at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:514)
                                                     at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2301)
                                                     at android.os.Binder.execTransact(Binder.java:446)

**Comment by mvysny** [comment]
Fixed in 3.39.1
