### ISSUE TITLE
Aedict crash: invalid value syuunei: not adj-i

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#595]
java.lang.IllegalArgumentException: Parameter base: invalid value syuunei: not adj-i
	at sk.baka.aedict.inflection.AdjectiveInflection.inflectADJI(AdjectiveInflection.java:55)
	at sk.baka.aedict.inflection.AdjectiveInflection.inflect(AdjectiveInflection.java:42)
	at sk.baka.aedict3.dict.VerbInflectionFragment.buildAndSetAdapterAdj(VerbInflectionFragment.java:164)
	at sk.baka.aedict3.dict.VerbInflectionFragment.buildAndSetAdapter(VerbInflectionFragment.java:139)
	at sk.baka.aedict3.dict.VerbInflectionFragment.onActivityCreated(VerbInflectionFragment.java:61)
	at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1970)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1092)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
	at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
	at sk.baka.aedict3.EdictEntryDetailActivity$MyPager.finishUpdate(EdictEntryDetailActivity.java:190)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1106)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:552)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:514)
	at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:495)
	at sk.baka.aedict3.EdictEntryDetailActivity.onTabSelected(EdictEntryDetailActivity.java:105)
	at android.support.v7.app.WindowDecorActionBar.selectTab(WindowDecorActionBar.java:619)
	at android.support.v7.app.WindowDecorActionBar$TabImpl.select(WindowDecorActionBar.java:1204)
	at android.support.v7.widget.ScrollingTabContainerView$TabClickListener.onClick(ScrollingTabContainerView.java:574)
	at android.view.View.performClick(View.java:4633)
	at android.view.View$PerformClick.run(View.java:19330)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:157)
	at android.app.ActivityThread.main(ActivityThread.java:5350)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by mvysny** [comment]
Fixed in 3.39.1
