### ISSUE TITLE
NPE in entry detail activity

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#621]
java.lang.RuntimeException: Unable to start activity ComponentInfo{sk.baka.aedict3/sk.baka.aedict3.EdictEntryDetailActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4077)
	at android.app.ActivityThread.-wrap15(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
	at sk.baka.aedict3.dict.SearchKanjiInJMDictFragment.performSearch(SearchKanjiInJMDictFragment.java:129)
	at sk.baka.aedict3.dict.SearchKanjiInJMDictFragment.tabVisible(SearchKanjiInJMDictFragment.java:124)
	at sk.baka.aedict3.util.android.HorizontalFragment.tabVisible(HorizontalFragment.java:86)
	at sk.baka.aedict3.EdictEntryDetailActivity$MyTab.tabVisible(EdictEntryDetailActivity.java:170)
	at sk.baka.aedict3.EdictEntryDetailActivity$1.onPageSelected(EdictEntryDetailActivity.java:222)
	at android.support.v4.view.ViewPager.dispatchOnPageSelected(ViewPager.java:1788)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:548)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:514)
	at android.support.v4.view.ViewPager.onRestoreInstanceState(ViewPager.java:1320)
	at android.view.View.dispatchRestoreInstanceState(View.java:14752)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3127)
	at android.view.View.restoreHierarchyState(View.java:14730)
	at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2035)
	at android.app.Activity.onRestoreInstanceState(Activity.java:1008)
	at android.app.Activity.performRestoreInstanceState(Activity.java:963)
	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1163)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2389)
	... 10 more

**Comment by mvysny** [comment]
Fixed in Aedict 3.39.8
