### ISSUE TITLE
Dropbox sync crashes

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#622]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/multiwindow.jar", zip file "/data/app/sk.baka.aedict3-1/base.apk"],nativeLibraryDirectories=[/data/app/sk.baka.aedict3-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libDropboxSync.so"
	at java.lang.Runtime.loadLibrary(Runtime.java:367)
	at java.lang.System.loadLibrary(System.java:988)
	at com.dropbox.sync.android.NativeLib.ensureLoaded(NativeLib.java:70)
	at com.dropbox.sync.android.NativeLib.<clinit>(NativeLib.java:32)
	at com.dropbox.sync.android.CoreAccountManager.initNativeLib(CoreAccountManager.java:228)
	at com.dropbox.sync.android.CoreAccountManager.<init>(CoreAccountManager.java:141)
	at com.dropbox.sync.android.DbxAccountManager.getInstance(DbxAccountManager.java:200)
	at com.dropbox.sync.android.DbxAccountManager.getInstance(DbxAccountManager.java:160)
	at com.dropbox.sync.android.DbxAccountManager.getInstance(DbxAccountManager.java:107)
	at sk.baka.aedict3.cloud.DropboxCloud.getManager(DropboxCloud.java:29)
	at sk.baka.aedict3.ConfigActivity.onPreferenceChange(ConfigActivity.java:220)
	at sk.baka.aedict3.ConfigActivity.access$000(ConfigActivity.java:63)
	at sk.baka.aedict3.ConfigActivity$1.onPreferenceChange(ConfigActivity.java:97)
	at android.preference.Preference.callChangeListener(Preference.java:1108)
	at android.preference.TwoStatePreference.onClick(TwoStatePreference.java:64)
	at android.preference.Preference.performClick(Preference.java:1163)
	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:263)
	at android.widget.AdapterView.performItemClick(AdapterView.java:339)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1555)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3747)
	at android.widget.AbsListView$3.run(AbsListView.java:5731)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6897)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by mvysny** [comment]
Unfortunately this cannot be fixed - Dropbox sync has been deprecated and will be abandoned at some point. Moreover, Dropbox guys will never provide Dropbox sync libraries for 64-bit processors, making that hardware effectively unsupported. I am sorry, but there is nothing I can do. Closing as WON'T FIX.
