### ISSUE TITLE
Parcel unmarshalling error

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#633]
java.lang.RuntimeException: Unable to start activity ComponentInfo{sk.baka.aedict3/sk.baka.aedict3.EdictEntryDetailActivity}: java.lang.RuntimeException: Parcel android.os.Parcel@2b0a6805: Unmarshalling unknown type code 3801188 at offset 1732
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2814)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2879)
	at android.app.ActivityThread.access$900(ActivityThread.java:182)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1475)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6141)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@2b0a6805: Unmarshalling unknown type code 3801188 at offset 1732
	at android.os.Parcel.readValue(Parcel.java:2222)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:2479)
	at android.os.BaseBundle.unparcel(BaseBundle.java:221)
	at android.os.Bundle.getSparseParcelableArray(Bundle.java:871)
	at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2255)
	at android.app.Activity.onRestoreInstanceState(Activity.java:1097)
	at android.app.Activity.performRestoreInstanceState(Activity.java:1042)
	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1175)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2787)
	... 10 more

**Comment by mvysny** [comment]
Removed any trace of Parcelable from my code. Hard to debug, unpredictable, and only slight performance increase: http://stackoverflow.com/questions/19672772/parcel-unmarshalling-unknown-type-code
Fixed in Aedict 3.39.9
