### ISSUE TITLE
Cannot connect to the internet: UnknownHostException

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#635]
`03-10 12:32:02.077: E/DownloaderService(30263): Failed to download dictionary data for dictionary JMDICT
03-10 12:32:02.077: E/DownloaderService(30263): java.net.UnknownHostException: Unable to resolve host "www.baka.sk": No address associated with hostname
03-10 12:32:02.077: E/DownloaderService(30263):  at java.net.InetAddress.lookupHostByName(InetAddress.java:470)
03-10 12:32:02.077: E/DownloaderService(30263):  at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
03-10 12:32:02.077: E/DownloaderService(30263):  at java.net.InetAddress.getAllByName(InetAddress.java:215)
03-10 12:32:02.077: E/DownloaderService(30263):  at com.android.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
03-10 12:32:02.077: E/DownloaderService(30263):  at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:188)
03-10 12:32:02.077: E/DownloaderService(30263):  at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:157)
03-10 12:32:02.077: E/DownloaderService(30263):  at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:100)
03-10 12:32:02.077: E/DownloaderService(30263):  at com.android.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:357)
03-10 12:32:02.077: E/DownloaderService(30263):  at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:340)
03-10 12:32:02.077: E/DownloaderService(30263):  at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
03-10 12:32:02.077: E/DownloaderService(30263):  at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
03-10 12:32:02.077: E/DownloaderService(30263):  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
03-10 12:32:02.077: E/DownloaderService(30263):  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
03-10 12:32:02.077: E/DownloaderService(30263):  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:231)
03-10 12:32:02.077: E/DownloaderService(30263):  at java.net.URL.openStream(URL.java:470)
03-10 12:32:02.077: E/DownloaderService(30263):  at sk.baka.aedict.dict.download.DictionaryFS.downloadMeta(DictionaryFS.java:81)
03-10 12:32:02.077: E/DownloaderService(30263):  at sk.baka.aedict.dict.download.DictionaryFS.downloadAllMetaIncludingCommercial(DictionaryFS.java:74)
03-10 12:32:02.077: E/DownloaderService(30263):  at sk.baka.aedict.dict.download.DictionaryFS.downloadMeta(DictionaryFS.java:64)
03-10 12:32:02.077: E/DownloaderService(30263):  at sk.baka.aedict3.dict.download.DownloaderService$DictionaryDownloader.downloadImpl(DownloaderService.java:389)
03-10 12:32:02.077: E/DownloaderService(30263):  at sk.baka.aedict3.dict.download.DownloaderService$DictionaryDownloader.access$800(DownloaderService.java:351)
03-10 12:32:02.077: E/DownloaderService(30263):  at sk.baka.aedict3.dict.download.DownloaderService$DictionaryDownloader$1.call(DownloaderService.java:377)
03-10 12:32:02.077: E/DownloaderService(30263):  at sk.baka.aedict.search.impl.LuceneCache.runExclusive(LuceneCache.java:129)
03-10 12:32:02.077: E/DownloaderService(30263):  at sk.baka.aedict3.dict.download.DownloaderService$DictionaryDownloader.download(DownloaderService.java:368)
03-10 12:32:02.077: E/DownloaderService(30263):  at sk.baka.aedict3.dict.download.DownloaderService$2.run(DownloaderService.java:267)
03-10 12:32:02.077: E/DownloaderService(30263):  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
03-10 12:32:02.077: E/DownloaderService(30263):  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-10 12:32:02.077: E/DownloaderService(30263):  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
03-10 12:32:02.077: E/DownloaderService(30263):  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
03-10 12:32:02.077: E/DownloaderService(30263):  at java.lang.Thread.run(Thread.java:818)
03-10 12:32:02.077: E/DownloaderService(30263): Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
03-10 12:32:02.077: E/DownloaderService(30263):  at libcore.io.Posix.android_getaddrinfo(Native Method)
03-10 12:32:02.077: E/DownloaderService(30263):  at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
03-10 12:32:02.077: E/DownloaderService(30263):  at java.net.InetAddress.lookupHostByName(InetAddress.java:451)
03-10 12:32:02.077: E/DownloaderService(30263):  ... 28 more`

**Comment by mvysny** [comment]
caused by GaiException: android_getaddrinfo failed: EAI_NODATA. Googling for this I found this: http://stackoverflow.com/questions/9475024/httpresponse-using-android-issue-execute-always-causes-exception

I will try to add <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/> and we will see.

**Comment by mvysny** [comment]
Added android.permission.ACCESS_WIFI_STATE
Marking as fixed in Aedict 3.39.9, please reopen if the problem persists.

**Comment by mvysny** [comment]
The customer's phone is Nexus 5, Android 6.0.1. I have found this bug report, perhaps this is an Android issue after all: https://code.google.com/p/android/issues/detail?id=197641

**Comment by mvysny** [comment]
Adding android.permission.ACCESS_WIFI_STATE did not helped, reverting back so that Aedict3 does not ask for unnecessary permissions.

**Comment by mvysny** [comment]
Unfortunately I have no idea what's causing this. Apparently there are no custom security settings for Aedict blocking internet access, perhaps this really is a bug in that particular Android phone? Unfortunately, there is nothing I can do, closing as bug in Android.
