### ISSUE TITLE
Crash when attempted to serialize FragmentFactory

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#640]
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = sk.baka.aedict3.util.android.FragmentFactory)
	at android.os.Parcel.writeSerializable(Parcel.java:1388)
	at android.os.Parcel.writeValue(Parcel.java:1335)
	at android.os.Parcel.writeList(Parcel.java:711)
	at android.os.Parcel.writeValue(Parcel.java:1284)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:638)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
	at android.os.Bundle.writeToParcel(Bundle.java:1096)
	at android.os.Parcel.writeBundle(Parcel.java:663)
	at android.support.v4.app.FragmentState.writeToParcel(Fragment.java:137)
	at android.os.Parcel.writeTypedArray(Parcel.java:1191)
	at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:385)
	at android.os.Parcel.writeParcelable(Parcel.java:1357)
	at android.os.Parcel.writeValue(Parcel.java:1262)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:638)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
	at android.os.Bundle.writeToParcel(Bundle.java:1096)
	at android.os.Parcel.writeBundle(Parcel.java:663)
	at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3113)
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3899)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6134)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by: java.io.NotSerializableException: android.os.Bundle
	at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1344)
	at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
	at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
	at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
	at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
	at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
	at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
	at android.os.Parcel.writeSerializable(Parcel.java:1383)
	... 26 more

**Comment by mvysny** [comment]
Fixed in Aedict 3.39.10
