### ISSUE TITLE
Aedict crashes when query contains ja/じゃ

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#656]
java.lang.RuntimeException: Unable to resume activity {sk.baka.aedict3/sk.baka.aedict3.search.MainActivity}: java.lang.RuntimeException: Failed to analyze 'あまのじゃ'
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2820)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2849)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2284)
	at android.app.ActivityThread.access$800(ActivityThread.java:143)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1242)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5124)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:613)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.RuntimeException: Failed to analyze 'あまのじゃ'
	at sk.baka.aedict.search.JMDictQuery.forGenericEnJpTerm(JMDictQuery.java:600)
	at sk.baka.aedict.search.JMDictQuery.access$000(JMDictQuery.java:39)
	at sk.baka.aedict.search.JMDictQuery$Builder.forGenericEnJpTerm(JMDictQuery.java:490)
	at sk.baka.aedict3.util.Config.newQuery(Config.java:671)
	at sk.baka.aedict3.search.MainActivity.getSearch(MainActivity.java:423)
	at sk.baka.aedict3.search.MainActivity.liveSearch(MainActivity.java:442)
	at sk.baka.aedict3.search.MainActivity.onResume(MainActivity.java:289)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1192)
	at android.app.Activity.performResume(Activity.java:5320)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2810)
	... 12 more
Caused by: java.lang.IllegalArgumentException: Parameter deinflectedVerbs: invalid value {}: must not be empty
	at sk.baka.aedict.inflection.Deinflections.<init>(Deinflections.java:126)
	at sk.baka.aedict.inflection.Deinflection.deinflectImpl(Deinflection.java:487)
	at sk.baka.aedict.inflection.Deinflection.deinflect(Deinflection.java:519)
	at sk.baka.aedict.search.JMDictQuery.getQuery(JMDictQuery.java:656)
	at sk.baka.aedict.search.JMDictQuery.forGenericEnJpTerm(JMDictQuery.java:587)
	... 21 more

**Comment by mvysny** [comment]
Fixed in Aedict 3.39.13
