### ISSUE TITLE
Aedict: NPE

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#657]
java.lang.RuntimeException: class sk.baka.aedict3.search.ResultActivity$ResultFragment: Loader failed: java.lang.RuntimeException: Failed to run query jp:Wしたがる OR jp:Wしたがるう OR jp:Wシタガル OR jp:Wshitagaru OR senseeng:shitagaru* OR sense:shitagaru*
	at sk.baka.aedict3.util.android.list.CheckableListFragment.handleLoaderError(CheckableListFragment.java:97)
	at sk.baka.aedict3.dict.AbstractEntryRefListFragment.handleDictionaryCrash(AbstractEntryRefListFragment.java:248)
	at sk.baka.aedict3.search.SearchResultFragment.handleLoaderError(SearchResultFragment.java:139)
	at sk.baka.aedict3.util.android.list.CheckableListFragment$1.onFailure(CheckableListFragment.java:116)
	at sk.baka.aedict3.util.android.LoaderEx$Loader.onFailure(LoaderEx.java:181)
	at sk.baka.aedict3.util.android.LoaderEx$Loader.access$100(LoaderEx.java:105)
	at sk.baka.aedict3.util.android.LoaderEx$Loader$1.run(LoaderEx.java:158)
	at android.os.Handler.handleCallback(Handler.java:730)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5103)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.RuntimeException: Failed to run query jp:Wしたがる OR jp:Wしたがるう OR jp:Wシタガル OR jp:Wshitagaru OR senseeng:shitagaru* OR sense:shitagaru*
	at sk.baka.aedict.search.impl.EdictSearch.findByQuery(EdictSearch.kt:45)
	at sk.baka.aedict.search.JMDictQuery.search(JMDictQuery.java:76)
	at sk.baka.aedict3.search.SearchResultFragment$MyLoader.loadItemsInBackground(SearchResultFragment.java:57)
	at sk.baka.aedict3.util.android.LoaderEx$Loader.run(LoaderEx.java:129)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.NullPointerException
	at sk.baka.aedict.search.lucene.DBQuery$Term.getWords(DBQuery.kt:535)
	at sk.baka.aedict.search.lucene.DBQuery$Term.getQueryAsString(DBQuery.kt:82)
	at sk.baka.aedict.search.lucene.DBQuery$Or.getQueryAsString(DBQuery.kt:208)
	at sk.baka.aedict.search.lucene.LuceneSearchUtils.search(LuceneSearchUtils.kt:115)
	at sk.baka.aedict.search.impl.LuceneCache$get$1.search(LuceneCache.kt:45)
	at sk.baka.aedict.search.impl.EdictSearch.findByQuery(EdictSearch.kt:39)
	... 8 more

**Comment by mvysny** [comment]
Turned out this is probably a bug in Kotlin: https://youtrack.jetbrains.com/issue/KT-11837
Fixed by implementing a workaround in Aedict 3.39.13
