### ISSUE TITLE
Crash when parsing query

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#667]
java.lang.RuntimeException: value: got : must be present and must not be whitespace-only and must not contain the following characters: +-&|!(){}[]^"~:\*?＊？
	at sk.baka.aedict.search.lucene.LuceneSearchUtils$Companion.checkContainsValidCharacters(LuceneSearchUtils.kt:221)
	at sk.baka.aedict.search.lucene.DBQuery$Term$Companion.term(DBQuery.kt:195)
	at sk.baka.aedict.search.lucene.DBQuery$Companion.term(DBQuery.kt:292)
	at sk.baka.aedict.search.lucene.DBQuery.term(DBQuery.kt)
	at sk.baka.aedict.search.KanjidicQuery.<init>(KanjidicQuery.java:69)
	at sk.baka.aedict.search.KanjidicQuery.search(KanjidicQuery.java:130)
	at sk.baka.aedict3.util.Config.newQuickQuery(Config.java:641)
	at sk.baka.aedict3.util.GlobalSearchButton$3.onQueryTextSubmit(GlobalSearchButton.java:84)
	at android.support.v7.widget.SearchView.onSubmitQuery(SearchView.java:1156)
	at android.support.v7.widget.SearchView.access$900(SearchView.java:101)
	at android.support.v7.widget.SearchView$9.onEditorAction(SearchView.java:1134)
	at android.widget.TextView.onEditorAction(TextView.java:4247)
	at com.android.internal.widget.EditableInputConnection.performEditorAction(EditableInputConnection.java:138)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:297)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:77)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4998)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:811)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:627)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by mvysny** [comment]
Fixed in 3.39.18. Kanjidic query would crash when only a small tsu was passed in.
