### ISSUE TITLE
Crash when searching for 'hot air balloon' in Kanjidic

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#684]
java.lang.IllegalArgumentException: Parameter query: invalid value hot air balloon: contains whitespaces (aG90IGFpciBiYWxsb29u)
                                                                     at sk.baka.aedict.search.QueryKana.<init>(QueryKana.kt:54)
                                                                     at sk.baka.aedict.search.KanjidicQuery.<init>(KanjidicQuery.java:52)
                                                                     at sk.baka.aedict.search.KanjidicQuery.search(KanjidicQuery.java:131)
                                                                     at sk.baka.aedict3.util.Config.newQuickQuery(Config.java:645)
                                                                     at sk.baka.aedict3.util.GlobalSearchButton$3.onQueryTextSubmit(GlobalSearchButton.java:84)
                                                                     at android.support.v7.widget.SearchView.onSubmitQuery(SearchView.java:1156)
                                                                     at android.support.v7.widget.SearchView.access$900(SearchView.java:101)
                                                                     at android.support.v7.widget.SearchView$9.onEditorAction(SearchView.java:1134)
                                                                     at android.widget.TextView.onEditorAction(TextView.java:4770)
                                                                     at com.android.internal.widget.EditableInputConnection.performEditorAction(EditableInputConnection.java:139)
                                                                     at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:304)
                                                                     at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5466)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by mvysny** [comment]
Fixed in Aedict 3.39.21
