### ISSUE TITLE
Deleting an item from RecentlyViewed crashes Aedict

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#687]
java.lang.ClassCastException: sk.baka.aedict3.search.RecentlyViewedFragment cannot be cast to sk.baka.aedict3.util.android.list.ActionModes$OnDelete
	at sk.baka.aedict3.listitems.SwipeSupport$SwipeAction$5.clicked(SwipeSupport.java:70)
	at sk.baka.aedict3.listitems.SwipeSupport$2.onSwipeEnd(SwipeSupport.java:160)
	at com.baoyz.swipemenulistview.SwipeMenuListView.onTouchEvent(SwipeMenuListView.java:174)
	at android.view.View.dispatchTouchEvent(View.java:7935)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2337)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2023)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2343)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2037)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2343)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2037)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2343)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2037)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2343)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2037)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2343)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2037)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2343)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2037)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2343)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2037)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2343)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2037)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2343)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2037)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2343)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2037)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2343)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2037)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2114)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1546)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2505)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2062)
	at android.view.View.dispatchPointerEvent(View.java:8126)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4580)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4451)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3997)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4047)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4016)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4123)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4024)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4180)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3997)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4047)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4016)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4024)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3997)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6279)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6241)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6195)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6427)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:140)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5486)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by mvysny** [comment]
Fixed in Aedict 3.39.22
