### ISSUE TITLE
SecurityException when accessing AnkiDroid

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#689]
java.lang.SecurityException: Permission not granted for: CardContentProvider.query /decks (sk.baka.aedict3)
	at android.os.Parcel.readException(Parcel.java:1599)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
	at android.content.ContentResolver.query(ContentResolver.java:491)
	at android.content.ContentResolver.query(ContentResolver.java:434)
	at com.ichi2.anki.api.AddContentApi.getDeckList(AddContentApi.java:387)
	at sk.baka.aedict3.util.export.AnkiDroidConfig.getDeckNames(AnkiDroidConfig.java:81)
	at sk.baka.aedict3.util.export.Exporter2.getDecks(Exporter2.java:666)
	at sk.baka.aedict3.util.export.ExportEditorDialog.<init>(ExportEditorDialog.java:140)
	at sk.baka.aedict3.util.export.ExportEditorDialog.show(ExportEditorDialog.java:70)
	at sk.baka.aedict3.util.export.Exporter2.addDirectlyToAnkiDroid(Exporter2.java:632)
	at sk.baka.aedict3.util.export.Exporter2.onMenuItemClicked(Exporter2.java:173)
	at sk.baka.aedict3.dict.JMDictEntryFragment.onOptionsItemSelected(JMDictEntryFragment.java:574)
	at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2070)
	at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:2159)
	at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:295)
	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:367)
	at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:147)
	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
	at android.support.v7.app.AppCompatDelegateImplV7.onMenuItemSelected(AppCompatDelegateImplV7.java:620)
	at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
	at android.support.v7.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:191)
	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3049)
	at android.widget.AbsListView$3.run(AbsListView.java:3886)
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by mvysny** [comment]
Reproduced on my phone, fixing now.

**Comment by mvysny** [comment]
Fixed in Aedict 3.39.23
