### ISSUE TITLE
Crashed in BitSet.valueOf

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#695]
`java.lang.RuntimeException: class sk.baka.aedict3.search.ResultActivity$ResultFragment: Loader failed: java.lang.RuntimeException: Failed to run query jp:W宗W
	at sk.baka.aedict3.util.android.list.CheckableListFragment.handleLoaderError(CheckableListFragment.java:99)
	at sk.baka.aedict3.dict.AbstractEntryRefListFragment.handleDictionaryCrash(AbstractEntryRefListFragment.java:248)
	at sk.baka.aedict3.search.SearchResultFragment.handleLoaderError(SearchResultFragment.java:139)
	at sk.baka.aedict3.util.android.list.CheckableListFragment$1.onFailure(CheckableListFragment.java:118)
	at sk.baka.aedict.util.LoaderEx$Loader.onFailure(LoaderEx.java:232)
	at sk.baka.aedict.util.LoaderEx$Loader.access$100(LoaderEx.java:149)
	at sk.baka.aedict.util.LoaderEx$Loader$1.run(LoaderEx.java:208)
	at android.os.Handler.handleCallback(Handler.java:587)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:130)
	at android.app.ActivityThread.main(ActivityThread.java:3691)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:670)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.RuntimeException: Failed to run query jp:W宗W
	at sk.baka.aedict.search.impl.EdictSearch.findByQuery(EdictSearch.kt:45)
	at sk.baka.aedict.search.impl.IJMDictSearch$DefaultImpls.findByJapanese(IJMDictSearch.kt:24)
	at sk.baka.aedict.search.impl.EdictSearch.findByJapanese(EdictSearch.kt:16)
	at sk.baka.aedict.search.SentenceAnalyzer.findLongestWord(SentenceAnalyzer.java:310)
	at sk.baka.aedict.search.SentenceAnalyzer.findLongestWord(SentenceAnalyzer.java:224)
	at sk.baka.aedict.search.SentenceAnalyzer.analyzeByWords(SentenceAnalyzer.java:111)
	at sk.baka.aedict.search.JMDictQuery.search(JMDictQuery.java:102)
	at sk.baka.aedict3.search.SearchResultFragment$MyLoader.loadItemsInBackground(SearchResultFragment.java:57)
	at sk.baka.aedict.util.LoaderEx$Loader.run(LoaderEx.java:179)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
	at java.lang.Thread.run(Thread.java:1019)
Caused by: java.lang.RuntimeException: Failed to run query jp:W宗W: jp:"W宗W"
	at sk.baka.aedict.search.lucene.LuceneSearchUtils.search(LuceneSearchUtils.kt:120)
	at sk.baka.aedict.search.impl.LuceneCache$get$1.search(LuceneCache.kt:45)
	at sk.baka.aedict.search.impl.EdictSearch.findByQuery(EdictSearch.kt:39)
	... 11 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Failed to invoke sk.baka.aedict.dict.JMDictEntry.readFrom(DataInput): java.lang.RuntimeException: Failed to invoke sk.baka.aedict.dict.JMDictEntry$ReadingData.unbox(Box)
	at sk.baka.aedict.util.Writables.read(Writables.java:276)
	at sk.baka.aedict.search.lucene.LuceneSearchUtils.toWritables(LuceneSearchUtils.kt:98)
	at sk.baka.aedict.search.lucene.LuceneSearchUtils.search(LuceneSearchUtils.kt:110)
	... 13 more
Caused by: java.lang.RuntimeException: Failed to invoke sk.baka.aedict.dict.JMDictEntry.readFrom(DataInput): java.lang.RuntimeException: Failed to invoke sk.baka.aedict.dict.JMDictEntry$ReadingData.unbox(Box)
	at sk.baka.aedict.util.Writables.read(Writables.java:256)
	at sk.baka.aedict.util.Writables.read(Writables.java:274)
	... 15 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at sk.baka.aedict.util.Writables.read(Writables.java:250)
	... 16 more
Caused by: java.lang.RuntimeException: Failed to invoke sk.baka.aedict.dict.JMDictEntry$ReadingData.unbox(Box)
	at sk.baka.aedict.util.Boxables.read(Boxables.java:51)
	at sk.baka.aedict.util.typedmap.Box.unbox(Box.java:397)
	at sk.baka.aedict.util.typedmap.AbstractTypedMap$BoxedListOfBoxes.unbox(AbstractTypedMap.java:665)
	at sk.baka.aedict.util.typedmap.AbstractTypedMap$Value.boxables(AbstractTypedMap.java:421)
	at sk.baka.aedict.dict.JMDictEntry.unbox(JMDictEntry.java:542)
	at sk.baka.aedict.dict.JMDictEntry.readFrom(JMDictEntry.java:515)
	... 19 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at sk.baka.aedict.util.Boxables.read(Boxables.java:49)
	... 24 more
Caused by: java.lang.RuntimeException: Failed to invoke sk.baka.aedict.kanji.PitchAccent$PitchData.unbox(Box)
	at sk.baka.aedict.util.Boxables.read(Boxables.java:51)
	at sk.baka.aedict.util.typedmap.Box.unbox(Box.java:397)
	at sk.baka.aedict.util.typedmap.AbstractTypedMap$BoxedBox.unbox(AbstractTypedMap.java:558)
	at sk.baka.aedict.util.typedmap.AbstractTypedMap$Value.boxable(AbstractTypedMap.java:410)
	at sk.baka.aedict.dict.JMDictEntry$ReadingData.unbox(JMDictEntry.java:426)
	... 27 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at sk.baka.aedict.util.Boxables.read(Boxables.java:49)
	... 31 more
Caused by: java.lang.NoSuchMethodError: java.util.BitSet.valueOf
	at sk.baka.aedict.util.typedmap.AbstractTypedMap$Value.bitSet(AbstractTypedMap.java:389)
	at sk.baka.aedict.kanji.PitchAccent$PitchData.unbox(PitchAccent.java:138)
	... 34 more`

**Comment by mvysny** [comment]
This crashes on Android 2.3.3 and older. Sorry guys, marking Aedict as requiring Android 11 or higher.

**Comment by mvysny** [comment]
Too bad that BitSet.valueOf has been added in API 19. Reopening.

**Comment by mvysny** [comment]
Fixed in Aedict 3.39.24, simply using custom-copied BitSet
