### ISSUE TITLE
java.lang.IllegalArgumentException: Parameter reading: invalid value でしめーとる: must contain hiragana only; kanji=粉 searchIn=[JMDICT]

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#705]
```
java.lang.IllegalArgumentException: Parameter reading: invalid value でしめーとる: must contain hiragana only; kanji=粉 searchIn=[JMDICT]
	at sk.baka.aedict.search.JMDictQuery.kanjiWithReading(JMDictQuery.java:983)
	at sk.baka.aedict3.dict.SearchKanjiInJMDictFragment.updateSpinnerItems(SearchKanjiInJMDictFragment.java:97)
	at sk.baka.aedict3.dict.SearchKanjiInJMDictFragment.onActivityCreated(SearchKanjiInJMDictFragment.java:63)
	at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1970)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1092)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
	at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
	at sk.baka.aedict3.EdictEntryDetailActivity$MyPager.finishUpdate(EdictEntryDetailActivity.java:189)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1106)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:552)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:514)
	at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:495)
	at sk.baka.aedict3.EdictEntryDetailActivity.onTabSelected(EdictEntryDetailActivity.java:104)
	at android.support.v7.app.WindowDecorActionBar.selectTab(WindowDecorActionBar.java:619)
	at android.support.v7.app.WindowDecorActionBar$TabImpl.select(WindowDecorActionBar.java:1204)
	at android.support.v7.widget.ScrollingTabContainerView$TabClickListener.onClick(ScrollingTabContainerView.java:574)
	at android.view.View.performClick(View.java:5609)
	at android.view.View$PerformClick.run(View.java:22262)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6077)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by mvysny** [comment]
Fixed in Aedict 3.39.27
