### ISSUE TITLE
Crash on older Androids

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#706]
```
java.lang.NoSuchMethodError: java.lang.Character.isBmpCodePoint
	at sk.baka.aedict.kanji.Kanji.isChar(Kanji.java:475)
	at sk.baka.aedict.kanji.KanjiUtils.getJlptLevel(KanjiUtils.java:411)
	at sk.baka.aedict.kanji.Kanji.getJLPTLevel(Kanji.java:309)
	at sk.baka.aedict.dict.Kanjidic2Entry.getJlptLevel(Kanjidic2Entry.kt:175)
	at sk.baka.aedict3.listitems.KanjiAdditionalInfo$7.get(KanjiAdditionalInfo.java:225)
	at sk.baka.aedict3.listitems.KanjiAdditionalInfo$Item.applyToKanjidicListItem(KanjiAdditionalInfo.java:96)
	at sk.baka.aedict3.listitems.KanjiAdditionalInfo.show(KanjiAdditionalInfo.java:58)
	at sk.baka.aedict3.listitems.KanjidicListItem.show(KanjidicListItem.java:77)
	at sk.baka.aedict3.dict.KanjiDicListFragment.show(KanjiDicListFragment.java:190)
	at sk.baka.aedict3.dict.KanjiDicListFragment.show(KanjiDicListFragment.java:33)
	at sk.baka.aedict3.util.android.list.CheckableListFragment$2.getView(CheckableListFragment.java:247)
	at android.widget.AbsListView.obtainView(AbsListView.java:2142)
```

**Comment by mvysny** [comment]
Fixed compatibility with older Androids

**Comment by mvysny** [comment]
java.lang.Character.isBmpCodePoint is present on Android 19 and later; Aedict should however support at least Android 15. Fixed.
