### ISSUE TITLE
NPE when starting Quiz from Notepad

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#729]
```
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.List sk.baka.aedict.userdatastorage.NotepadCategoryDB.getContent()' on a null object reference
	at sk.baka.aedict3.NotepadActivity$6.onClick(NotepadActivity.java:346)
	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:160)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5219)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
```

**Comment by mvysny** [comment]
Fixed in Aedict 3.39.29
