### ISSUE TITLE
aedict crashes on ACTION_SEARCH_JMDICT intent

### ISSUE THREAD

**Issue by blastrock** [mvysny/aedict#784]
The following lines of kotlin make aedict3 crash:

```kotlin
            val intent = Intent("sk.baka.aedict3.action.ACTION_SEARCH_JMDICT")
            intent.putExtra("kanjis", "日")
            startActivity(intent)
```

I should have sent you a bunch of bug reports through android on Tuesday, and one more right now :)

Is this a bug in aedict, or did I misuse the API?

**Comment by mvysny** [comment]
Hey, thanks for letting me know! The call seems totally legit. I can see several crashes in my console, but nothing that can be directly associated with this bug report. Can you please paste the Aedict stacktrace?

**Comment by blastrock** [comment]
Haha... Should have done that before... I got the problem, I never started aedict on this phone before ^^

```
07-29 11:09:47.256  4173  4173 D AndroidRuntime: Shutting down VM
07-29 11:09:48.014  4173  4173 E AndroidRuntime: FATAL EXCEPTION: main
07-29 11:09:48.014  4173  4173 E AndroidRuntime: Process: sk.baka.aedict3, PID: 4173
07-29 11:09:48.014  4173  4173 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{sk.baka.aedict3/sk.baka.aedict3.search.ResultActivity}: java.lang.RuntimeException: Failed to analyze '日' (5pel)
07-29 11:09:48.014  4173  4173 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
07-29 11:09:48.014  4173  4173 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
07-29 11:09:48.014  4173  4173 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
07-29 11:09:48.014  4173  4173 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
07-29 11:09:48.014  4173  4173 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-29 11:09:48.014  4173  4173 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
07-29 11:09:48.014  4173  4173 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
07-29 11:09:48.014  4173  4173 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-29 11:09:48.014  4173  4173 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-29 11:09:48.014  4173  4173 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-29 11:09:48.014  4173  4173 E AndroidRuntime: Caused by: java.lang.RuntimeException: Failed to analyze '日' (5pel)
07-29 11:09:48.014  4173  4173 E AndroidRuntime: 	at sk.baka.aedict.search.JMDictQuery$Companion.forGenericEnJpTerm(JMDictQuery.kt:418)
07-29 11:09:48.014  4173  4173 E AndroidRuntime: 	at sk.baka.aedict.search.JMDictQuery$Companion.access$forGenericEnJpTerm(JMDictQuery.kt:360)
07-29 11:09:48.014  4173  4173 E AndroidRuntime: 	at sk.baka.aedict.search.JMDictQuery$Builder.forGenericEnJpTerm(JMDictQuery.kt:280)
07-29 11:09:48.014  4173  4173 E AndroidRuntime: 	at sk.baka.aedict3.search.ResultActivity$Companion.parseActionSearchJMDict(ResultActivity.kt:298)
07-29 11:09:48.014  4173  4173 E AndroidRuntime: 	at sk.baka.aedict3.search.ResultActivity$Companion.parseActionSearchJMDict(ResultActivity.kt:254)
07-29 11:09:48.014  4173  4173 E AndroidRuntime: 	at sk.baka.aedict3.search.ResultActivity.getQueryFromIntent(ResultActivity.kt:111)
07-29 11:09:48.014  4173  4173 E AndroidRuntime: 	at sk.baka.aedict3.search.ResultActivity.onCreate(ResultActivity.kt:165)
07-29 11:09:48.014  4173  4173 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6251)
07-29 11:09:48.014  4173  4173 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
07-29 11:09:48.014  4173  4173 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
07-29 11:09:48.014  4173  4173 E AndroidRuntime: 	... 9 more
07-29 11:09:48.014  4173  4173 E AndroidRuntime: Caused by: java.lang.IllegalStateException: The dictionary JMDICT is not available locally; available dictionaries: []
07-29 11:09:48.014  4173  4173 E AndroidRuntime: 	at sk.baka.aedict.search.impl.LuceneCache.getJMDict(LuceneCache.kt:35)
07-29 11:09:48.014  4173  4173 E AndroidRuntime: 	at sk.baka.aedict.search.SentenceAnalyzer$Companion$READING_RESOLVER$1.resolve(SentenceAnalyzer.kt:279)
07-29 11:09:48.014  4173  4173 E AndroidRuntime: 	at sk.baka.aedict.inflection.Deinflection.deinflect(Deinflection.java:548)
07-29 11:09:48.014  4173  4173 E AndroidRuntime: 	at sk.baka.aedict.search.JMDictQuery$Companion.getQuery(JMDictQuery.kt:480)
07-29 11:09:48.014  4173  4173 E AndroidRuntime: 	at sk.baka.aedict.search.JMDictQuery$Companion.forGenericEnJpTerm(JMDictQuery.kt:411)
07-29 11:09:48.014  4173  4173 E AndroidRuntime: 	... 18 more
07-29 11:09:48.020   797   807 W ActivityManager:   Force finishing activity sk.baka.aedict3/.search.ResultActivity
```

Sorry for bothering you for this, I guess you can close this bug :)

**Comment by mvysny** [comment]
No worries :-) yeah the exception shows that the dictionaries are missing and must be downloaded. Closing
