### ISSUE TITLE
Notepad crashees on quiz from category

### ISSUE THREAD

**Issue by milk-shake** [mvysny/aedict#805]
I'm not sure what extra information you need but the list is 75 words long and works. If I add another word the quiz crashes to black and then back to the notepad.

**Comment by mvysny** [comment]
Hi, thanks for letting me know, and I apologize for the crash. Which version of Aedict are you using? I see no crashes reported in my console unfortunately; if you'd like to help me to obtain the crash from your phone, please follow this tutorial: http://aedict.eu/faq.html the "Aedict 3 log" section.

**Comment by milk-shake** [comment]
I'm on v3.45 (latest according to the play store)

I've since removed and reinstalled and had no crashes until I set the quiz to 100 items, then it crashes without fail. 50 items works fine which is an acceptable work around.

Please see the log below - it's from just before I start the quiz (and change the settings) to the crash

Much appreciated!

```

10-12 09:10:49.247: W//system/bin/hwservicemanager(356): getTransportFromManifest: Cannot find entry android.hardware.graphics.mapper@2.0::IMapper in either framework or device manifest, using default transport.
10-12 09:10:49.251: I/vndksupport(19076): sphal namespace is not configured for this process. Loading /vendor/lib64/hw/gralloc.msm8992.so from the current namespace instead.
10-12 09:10:49.283: I/ActivityManager(3057): Displayed sk.baka.aedict3/.search.MainActivity: +655ms (total +769ms)
10-12 09:10:49.284: I/Aedict:LoaderEx(19076): Loader #1 RecentlyViewed canceled: canceled
10-12 09:10:49.287: I/Aedict:CheckableListVi*(19076): Got data: 15 item(s)
10-12 09:10:49.295: W/ResourceType(19076): Invalid package identifier when getting bag for resource number 0x00000423
10-12 09:10:49.296: W/ResourceType(19076): Invalid package identifier when getting bag for resource number 0x0000041a
10-12 09:10:49.307: I/Aedict:FileStorage(19076): Loaded SimpleSRS in 3ms (read: 3ms)
10-12 09:10:49.567: I/Aedict:FileStorage(19076): Loaded TheNotepad in 252ms (read: 252ms)
10-12 09:10:49.588: W/ResourceType(19076): Invalid package identifier when getting bag for resource number 0x00000423
10-12 09:10:49.589: W/ResourceType(19076): Invalid package identifier when getting bag for resource number 0x0000041a
10-12 09:10:49.591: I/zygote64(19076): Deoptimizing boolean sk.baka.aedict.util.UtilKt.intersects(java.util.Set, java.util.Set) due to JIT inline cache
10-12 09:10:49.596: W/ResourceType(19076): Invalid package identifier when getting bag for resource number 0x00000423
10-12 09:10:49.596: W/ResourceType(19076): Invalid package identifier when getting bag for resource number 0x0000041a
10-12 09:10:49.603: W/ResourceType(19076): Invalid package identifier when getting bag for resource number 0x00000423
10-12 09:10:49.603: W/ResourceType(19076): Invalid package identifier when getting bag for resource number 0x0000041a
10-12 09:10:49.612: W/ResourceType(19076): Invalid package identifier when getting bag for resource number 0x00000423
10-12 09:10:49.612: W/ResourceType(19076): Invalid package identifier when getting bag for resource number 0x0000041a
10-12 09:10:49.619: W/ResourceType(19076): Invalid package identifier when getting bag for resource number 0x00000423
10-12 09:10:49.619: W/ResourceType(19076): Invalid package identifier when getting bag for resource number 0x0000041a
10-12 09:10:49.625: W/ResourceType(19076): Invalid package identifier when getting bag for resource number 0x00000423
10-12 09:10:49.625: W/ResourceType(19076): Invalid package identifier when getting bag for resource number 0x0000041a
10-12 09:10:49.627: I/zygote64(19076): Do full code cache collection, code=119KB, data=74KB
10-12 09:10:49.627: I/zygote64(19076): After code cache collection, code=105KB, data=55KB
10-12 09:10:49.638: W/ResourceType(19076): No package identifier when getting name for resource number 0x00000000
10-12 09:10:49.639: I/chatty(19076): uid=10141(u0_a141) sk.baka.aedict3 identical 5 lines
10-12 09:10:49.639: W/ResourceType(19076): No package identifier when getting name for resource number 0x00000000
10-12 09:10:49.639: W/View(19076): dispatchProvideAutofillStructure(): not laid out, ignoring
10-12 09:10:49.640: I/chatty(19076): uid=10141(u0_a141) sk.baka.aedict3 identical 35 lines
10-12 09:10:49.640: W/View(19076): dispatchProvideAutofillStructure(): not laid out, ignoring
10-12 09:10:49.641: W/Binder(3057): Outgoing transactions from this process must be FLAG_ONEWAY
10-12 09:10:49.641: W/Binder(3057): java.lang.Throwable
10-12 09:10:49.641: W/Binder(3057): 	at android.os.BinderProxy.transact(Binder.java:736)
10-12 09:10:49.641: W/Binder(3057): 	at android.app.assist.AssistStructure$ParcelTransferReader.fetchData(AssistStructure.java:407)
10-12 09:10:49.641: W/Binder(3057): 	at android.app.assist.AssistStructure$ParcelTransferReader.go(AssistStructure.java:343)
10-12 09:10:49.641: W/Binder(3057): 	at android.app.assist.AssistStructure.ensureData(AssistStructure.java:2096)
10-12 09:10:49.641: W/Binder(3057): 	at com.android.server.autofill.Session$1.send(Session.java:200)
10-12 09:10:49.641: W/Binder(3057): 	at com.android.server.am.ActivityManagerService.reportAssistContextExtras(ActivityManagerService.java:13137)
10-12 09:10:49.641: W/Binder(3057): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2466)
10-12 09:10:49.641: W/Binder(3057): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2935)
10-12 09:10:49.641: W/Binder(3057): 	at android.os.Binder.execTransact(Binder.java:674)
10-12 09:10:49.642: I/AssistStructure(19076): Flattened final assist data: 14748 bytes, containing 1 windows, 77 views
10-12 09:10:49.643: I/Aedict:LoaderEx(19076): Loader #2 RecentlyViewed: returned 15 item(s) in 359ms (scheduled: 1ms, running: 358ms)
10-12 09:10:49.645: I/Aedict:CheckableListVi*(19076): Got data: 15 item(s)
10-12 09:10:49.659: W/ResourceType(19076): Invalid package identifier when getting bag for resource number 0x00000423
10-12 09:10:49.659: W/ResourceType(19076): Invalid package identifier when getting bag for resource number 0x0000041a
10-12 09:10:49.662: I/zygote64(19076): Deoptimizing boolean sk.baka.aedict.util.UtilKt.intersects(java.util.Set, java.util.Set) due to JIT inline cache
10-12 09:10:49.668: W/ResourceType(19076): Invalid package identifier when getting bag for resource number 0x00000423
10-12 09:10:49.668: W/ResourceType(19076): Invalid package identifier when getting bag for resource number 0x0000041a
10-12 09:10:49.669: I/AssistStructure(3057): Flattened final assist data: 12468 bytes, containing 1 windows, 77 views
10-12 09:10:49.670: I/zygote64(19076): Deoptimizing boolean sk.baka.aedict.util.UtilKt.intersects(java.util.Set, java.util.Set) due to JIT inline cache
10-12 09:10:49.675: W/ResourceType(19076): Invalid package identifier when getting bag for resource number 0x00000423
10-12 09:10:49.675: W/ResourceType(19076): Invalid package identifier when getting bag for resource number 0x0000041a
10-12 09:10:49.681: W/ResourceType(19076): Invalid package identifier when getting bag for resource number 0x00000423
10-12 09:10:49.681: W/ResourceType(19076): Invalid package identifier when getting bag for resource number 0x0000041a
10-12 09:10:49.690: W/ResourceType(19076): Invalid package identifier when getting bag for resource number 0x00000423
10-12 09:10:49.690: W/ResourceType(19076): Invalid package identifier when getting bag for resource number 0x0000041a
10-12 09:10:49.697: W/ResourceType(19076): Invalid package identifier when getting bag for resource number 0x00000423
10-12 09:10:49.697: W/ResourceType(19076): Invalid package identifier when getting bag for resource number 0x0000041a
10-12 09:10:49.703: W/ResourceType(19076): Invalid package identifier when getting bag for resource number 0x00000423
10-12 09:10:49.703: W/ResourceType(19076): Invalid package identifier when getting bag for resource number 0x0000041a
10-12 09:10:49.712: I/zygote64(19076): Do partial code cache collection, code=118KB, data=80KB
10-12 09:10:49.712: I/zygote64(19076): After code cache collection, code=115KB, data=78KB
10-12 09:10:49.712: I/zygote64(19076): Increasing code cache capacity to 512KB
10-12 09:10:50.495: I/CastDatabase(5875): Saving the database
10-12 09:10:50.496: I/SQLiteCastStore(5875): Saving 0 CastNetworkInfo instances, 0 CastDeviceInfo instances, 0 paired guest mode devices.
10-12 09:10:50.531: E/SQLiteCastStore(5875): End saving paired guest mode devices
10-12 09:10:54.683: W/RemoteFillService(3057): Not handling { when=-5ms what=3 target=com.android.internal.os.HandlerCaller$MyHandler } as service for ComponentInfo{com.google.android.gms/com.google.android.gms.autofill.service.AutofillService} is already destroyed
10-12 09:11:05.774: W/ContextHubService(3057): Sending msg of type 0 len 10 to app 476f6f676c00100b on hub 0
10-12 09:11:05.774: I/ContextHubHalAdapter(3057): Sending msg of type 0, size 10 to app 0x476f6f676c00100b
10-12 09:11:06.086: D/ContextHubService(3057): Sending message 1025 version 0 from hubHandle 0, appInstance 13, callBackCount 1
10-12 09:11:06.093: W/nanohub(3057): osLog: hostIntfFindHandler failed with: 3
10-12 09:11:10.448: D/WificondControl(3057): Scan result ready event
```

**Comment by mvysny** [comment]
Thanks! Unfortunately the log does not contain the stacktrace of the crash (the `W/Binder(3057)` is something else). I tried to set quiz length to 100 on my phone and it works. It could perhaps be caused by out of memory issues? Can you please try to observe the log some more? Or perhaps Aedict is just killed by Android, without any trace? Hard to say...

**Comment by mvysny** [comment]
Maybe unrelated, but this error has been reported by someone's phone: `java.io.IOException: write failed: ENOSPC (No space left on device)` . Can you please check that you have enough space on your device?

**Comment by mvysny** [comment]
No activity for more than a month, closing.
