### ISSUE TITLE
Crash on Android 9 in ValueAnimator

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#854]
The problem is that Aedict hosts a copied-out class ValueAnimator, which no longer works with SDK 28. I don't know why I copied that class out (it was probably because of fragmentation, or maybe because it's starting SDK 11?). I've reverted to use the SDK ValueAnimator, but if it fails, I'll have to bring it back.

```
Caused by java.lang.NoSuchMethodException: init []
       at java.lang.Class.getMethod(Class.java:2068)
       at java.lang.Class.getDeclaredMethod(Class.java:2047)
       at sk.baka.aedictkanjidrawpractice.util.android.ValueAnimator.<clinit>(ValueAnimator.java:83)
       at sk.baka.aedictkanjidrawpractice.util.android.ValueAnimator.ofFloat(ValueAnimator.java:368)
       at sk.baka.aedictkanjidrawpractice.util.android.KanjiDrawView.startStrokeAnimation(KanjiDrawView.kt:270)
       at sk.baka.aedictkanjidrawpractice.util.android.KanjiDrawView.startStrokeAnimation$default(KanjiDrawView.kt:261)
       at sk.baka.aedictkanjidrawpractice.KanjiDrawPracticeActivity.onResume(KanjiDrawPracticeActivity.kt:241)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
       at android.app.Activity.performResume(Activity.java:7300)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3777)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3817)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6680)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by mvysny** [comment]
Fixed in Aedict 3.50.10
