### ISSUE TITLE
SecurityException reading clipboard

### ISSUE THREAD

**Issue by mvysny** [mvysny/aedict#874]
```
Fatal Exception: java.lang.SecurityException: UID 10087 does not have permission to content://org.nextcloud.files/external_files/emulated/0/Android/media/com.nextcloud.client/nextcloud/freddyncalm%40arufureedo.zapto.org%252Fnextcloud/Clases/234%E3%82%AF%E3%83%A9%E3%82%B9.txt [user 0]
       at android.os.Parcel.createException(Parcel.java:1950)
       at android.os.Parcel.readException(Parcel.java:1918)
       at android.os.Parcel.readException(Parcel.java:1868)
       at android.content.IClipboard$Stub$Proxy.getPrimaryClip(IClipboard.java:215)
       at android.content.ClipboardManager.getPrimaryClip(ClipboardManager.java:130)
       at sk.baka.aedictkanjidrawpractice.util.android.KViewsKt.getTextSafe(KViews.kt:147)
       at sk.baka.aedict3.search.MainActivity$omniboxChangeListener$1.afterTextChanged(MainActivity.kt:243)
       at android.widget.TextView.sendAfterTextChanged(TextView.java:9802)
       at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:12554)
       at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1288)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:591)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:521)
       at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:41)
       at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:843)
       at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:616)
       at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:396)
       at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:85)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6863)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.checkGrantUriPermissionLocked(ActivityManagerService.java:11298)
	at com.android.server.am.ActivityManagerService.grantUriPermissionLocked(ActivityManagerService.java:11364)
	at com.android.server.am.ActivityManagerService.grantUriPermissionFromOwner(ActivityManagerService.java:11802)
	at com.android.server.clipboard.ClipboardService.grantUriLocked(ClipboardService.java:534)
	at com.android.server.clipboard.ClipboardService.grantItemLocked(ClipboardService.java:549)
```
OnePlus, Android 9.

**Comment by mvysny** [comment]
Fixed in Aedict 3.50.14

**Comment by o8o78** [comment]
hi there, how did you fix this? af keeps reporting me similar crashes these days...

**Comment by mvysny** [comment]
Don't remember unfortunately; but I think I had to use a different way to get the clipboard - different API call.
