### ISSUE TITLE
Aedict crashes on startup since latest update

### ISSUE THREAD

**Issue by BenjaminBrandtner** [mvysny/aedict#990]
After the latest update, Aedict crashes immeadiately on startup on my (admittedly ancient) phone.

phone brand and maker: **Samsung Galaxy S7**
exact Android version: **8.0.0**

This is what I found in the crash report generated by android:
```
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: FATAL EXCEPTION: main
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: Process: sk.baka.aedict3, PID: 15082
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: java.lang.RuntimeException: Unable to create application sk.baka.aedict3.AedictApp: java.lang.IllegalArgumentException: Could not deserialize [-84, -19, 0, 5, 115, 114, 0, 53, 115, 107, 46, 98, 97, 107, 97, 46, 97, 101, 100, 105, 99, 116, 46, 117, 115, 101, 114, 100, 97, 116, 97, 115, 116, 111, 114, 97, 103, 101, 46, 117, 109, 110, 46, 73, 100, 120, 67, 97, 116, 101, 103, 111, 114, 121, 79, 114, 100, 105, 110, 97, 108, 40, 114, -72, 99, 6, 122, -78, -100, 2, 0, 2, 70, 0, 7, 111, 114, 100, 105, 110, 97, 108, 76, 0, 15, 111, 119, 110, 101, 114, 67, 97, 116, 101, 103, 111, 114, 121, 73, 100, 116, 0, 16, 76, 106, 97, 118, 97, 47, 117, 116, 105, 108, 47, 85, 85, 73, 68, 59, 120, 112, 66, -58, 0, 0, 115, 114, 0, 14, 106, 97, 118, 97, 46, 117, 116, 105, 108, 46, 85, 85, 73, 68, -68, -103, 3, -9, -104, 109, -123, 47, 2, 0, 2, 74, 0, 12, 108, 101, 97, 115, 116, 83, 105, 103, 66, 105, 116, 115, 74, 0, 11, 109, 111, 115, 116, 83, 105, 103, 66, 105, 116, 115, 120, 112, -103, -35, -124, 69, -36, 113, 35, -6, 7, -47, -15, -91, -88, -47, 66, 102] [1.4.197/0]
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6065)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6944)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Could not deserialize [-84, -19, 0, 5, 115, 114, 0, 53, 115, 107, 46, 98, 97, 107, 97, 46, 97, 101, 100, 105, 99, 116, 46, 117, 115, 101, 114, 100, 97, 116, 97, 115, 116, 111, 114, 97, 103, 101, 46, 117, 109, 110, 46, 73, 100, 120, 67, 97, 116, 101, 103, 111, 114, 121, 79, 114, 100, 105, 110, 97, 108, 40, 114, -72, 99, 6, 122, -78, -100, 2, 0, 2, 70, 0, 7, 111, 114, 100, 105, 110, 97, 108, 76, 0, 15, 111, 119, 110, 101, 114, 67, 97, 116, 101, 103, 111, 114, 121, 73, 100, 116, 0, 16, 76, 106, 97, 118, 97, 47, 117, 116, 105, 108, 47, 85, 85, 73, 68, 59, 120, 112, 66, -58, 0, 0, 115, 114, 0, 14, 106, 97, 118, 97, 46, 117, 116, 105, 108, 46, 85, 85, 73, 68, -68, -103, 3, -9, -104, 109, -123, 47, 2, 0, 2, 74, 0, 12, 108, 101, 97, 115, 116, 83, 105, 103, 66, 105, 116, 115, 74, 0, 11, 109, 111, 115, 116, 83, 105, 103, 66, 105, 116, 115, 120, 112, -103, -35, -124, 69, -36, 113, 35, -6, 7, -47, -15, -91, -88, -47, 66, 102] [1.4.197/0]
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at org.h2.mvstore.DataUtils.newIllegalArgumentException(DataUtils.java:844)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at org.h2.mvstore.type.ObjectDataType.deserialize(ObjectDataType.java:376)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at org.h2.mvstore.type.ObjectDataType$SerializedObjectType.read(ObjectDataType.java:1555)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at org.h2.mvstore.type.ObjectDataType.read(ObjectDataType.java:231)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at org.h2.mvstore.type.ObjectDataType.read(ObjectDataType.java:114)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at org.h2.mvstore.Page.read(Page.java:711)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at org.h2.mvstore.Page.read(Page.java:186)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at org.h2.mvstore.MVStore.readPage(MVStore.java:1936)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at org.h2.mvstore.MVMap.readPage(MVMap.java:698)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at org.h2.mvstore.MVMap.setRootPos(MVMap.java:708)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at org.h2.mvstore.MVStore.openMap(MVStore.java:474)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at org.h2.mvstore.MVStore.openMap(MVStore.java:431)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at com.gitlab.mvysny.umn.core.MvstoreUtilityMap.<init>(MvstoreUMN.kt:170)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at com.gitlab.mvysny.umn.core.MvstoreUMN.openUtilityMap(MvstoreUMN.kt:139)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at com.gitlab.mvysny.umn.core.IndexingUMN$IndexImpl.<init>(IndexingUMN.kt:139)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at com.gitlab.mvysny.umn.core.IndexingUMN$IndexDef.toImpl$umn_core(IndexingUMN.kt:103)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at com.gitlab.mvysny.umn.core.IndexingUMN.<init>(IndexingUMN.kt:43)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at sk.baka.aedict.userdatastorage.umn.UserDataUMN.<init>(UMNUtils.kt:103)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at sk.baka.aedict3.util.KConfig$StorageType$UMN.createUserData(KConfig.kt:376)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at sk.baka.aedict3.AedictApp.initializeUserData(AedictApp.java:256)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at sk.baka.aedict3.AedictApp.onCreate(AedictApp.java:138)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1125)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6062)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	... 8 more
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: Caused by: java.io.InvalidClassException: sk.baka.aedict.userdatastorage.umn.IdxCategoryOrdinal; local class incompatible: stream classdesc serialVersionUID = 2914594644312109724, local class serialVersionUID = -4760944258773679866
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:606)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1626)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1777)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1354)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:374)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	at org.h2.mvstore.type.ObjectDataType.deserialize(ObjectDataType.java:374)
07-21 06:43:14.722 10228 15082 15082 E AndroidRuntime: 	... 29 more
```

Screenshot:
![Screenshot_20240721-081450_Samsung Experience Home](https://github.com/user-attachments/assets/d43f44f7-0795-4700-bd5a-c925620d7d1e)

**Comment by mvysny** [comment]
Thank you for letting me know, and I'm sorry for the issue. The issue is already fixed, and one user is testing it. Once it's tested successfully, I'll make a release today.

**Comment by mvysny** [comment]
Fixed in Aedict 3.51.6

**Comment by mjaj** [comment]
Unfortunately, the same happens again with version 3.51.6, on two different devices. The previous version crashed, it worked after I uninstall the whole app and installed it again. Now, after the bugfix update, it crashes again right after start. I did not yet reinstall again.

**Comment by mvysny** [comment]
Could you please send me a log trace from your app?

**Comment by mjaj** [comment]
> Could you please send me a log trace from your app?

I don't really know where to find this. Can you give me a hint?

**Comment by mvysny** [comment]
There's http://aedict.eu/faq.html "Aedict 3 log", but you can download Android studio and connect your phone via usb cable with it, then there's the "log" section.

**Comment by statiq-q** [comment]
Hi Martin,

I've got the same problem as mjaj, I'm on a Samsung A52, with Android 14. July 1st update.

Aedict crashes on startup since about a month. Uninstalling it fixes the problem for a while, then the systematic crashes on launch come back.

I didn't report the bug before because I didn't have a github account and hoped the fixes you were working on would take care of of it.

**Comment by mvysny** [comment]
Do you perhaps have synchronization with Aedict Online enabled? If yes, that could be the source of the problem. Basically different Android phones stored the data a bit in a different way, and the data was backed up in Aedict Online. When I found out, I've made sure to unify the data storage, but unfortunately for some phones that means that the data isn't readable anymore.

Please disable syncing with Aedict Online if you're not really using it; or alternatively create a new account at Aedict Online. Unfortunately, either way, your data is most probably lost :(

**Comment by statiq-q** [comment]
Thanks for you answer.

I didn't have synch with Aedict Online enabled initially when the crash-at-launch bug appeared, in order to try to fix the problem I tried to uninstall and reinstall Aedict from Google play and realized my data - which was stored locally at that point - was gone :(

I've now enabled synchronization with Aedict Online (which had some older data in it), and it's working. So, so far so good. 

I use Aedict every day so I'd rather have it working with an older version of my data, than to not have it at all. 

Taking this opportunity to thank for all the work you put in that project, the "Kanji parts / junctures" feature really is a life saver when looking up and studying Kanji!
